#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x polybar > /dev/null || polybar solidus &
pgrep -x dunst > /dev/null || dunst &
pgrep -x picom > /dev/null || picom --experimental-backends -b
pgrep -x redshift > /dev/null || redshift -t 5500:4000 &
pgrep -x nm-applet > /dev/null || nm-applet &  

bspc monitor -d I II III IV V # VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           6
bspc config top_padding         27

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#c69ef7" 
bspc config focused_border_color "#bdf79b"

bspc rule -a Emacs state=tiled

bspc config focus_follows_pointer true

cronwhip --start now --interval 24

xsetroot -cursor_name left_ptr
xinput set-prop "Synaptics TM3336-001" "libinput Tapping Enabled" 1
xinput set-prop "Synaptics TM3336-001" "libinput Natural Scrolling Enabled" 1

xset -dpms
xset s off
